# copy this file and then dont push it again, add it to git ignore
# (by going into .gitignore and typing db.properties)
# also if you have mysql installed
# and want this to run then use this command when you login as root:

#CREATE USER 'iposca_app'@'localhost' IDENTIFIED BY 'choose_a_password';
#GRANT ALL PRIVILEGES ON ipos_ca.* TO 'iposca_app'@'localhost';

# db.url=jdbc:mysql://localhost:3306/ipos_ca
# # db.user=iposca_app
# # db.password=iposcapassword
# db.user=root
# db.password=root


# db.url=${DATABASE_URL:jdbc:postgresql://interchange.proxy.rlwy.net:32051/railway}
# db.username=${DATABASE_USERNAME:postgres}
# db.password=${DATABASE_PASSWORD:lErRygBqPGvHztVNpppUnpSQslZfwRbx}


db.url=jdbc:postgresql://interchange.proxy.rlwy.net:32051/railway
db.username=postgres
db.password=lErRygBqPGvHztVNpppUnpSQslZfwRbx